name: Prime Choice Application Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

env:
  AWS_REGION: us-east-1
  DOCKERHUB_USERNAME: cytemi5000
  IMAGE_NAME: primechoice
  EKS_CLUSTER_NAME: my-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
          kubectl get nodes

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --no-cache \
            --build-arg DJANGO_SETTINGS_MODULE=primechoice.settings \
            --build-arg SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} .

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push Docker Image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}

      - name: Update Image Tag
        working-directory: kubernetes
        run: |
          sed -i "s|image: .*|image: $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}|g" django-deployment.yaml

      - name: Create namespace
        working-directory: kubernetes
        run: |
          kubectl apply -f namespace.yaml
      - name: Delete old Postgres PVC
        run: |
          kubectl delete pvc postgres-pvc -n django-app --ignore-not-found=true
      - name: checks
        working-directory: kubernetes
        run: |
          kubectl get storageclass
          kubectl get pvc -n django-app
          kubectl get pods -n django-app
      - name: Deploy to EKS
        working-directory: kubernetes
        run: |
          kubectl apply -f django-configmap.yaml
          kubectl apply -f postgres-secret.yaml
          kubectl apply -f django-secret.yaml
          kubectl apply -f postgres-pvc.yaml
          kubectl apply -f postgres-deployment.yaml
          kubectl apply -f postgres-service.yaml
          kubectl apply -f django-deployment.yaml
          kubectl apply -f django-service.yaml

      - name: Debug Storage
        run: |
          echo "=== STORAGE CLASSES ==="
          kubectl get storageclass

          echo "=== PVC STATUS ==="
          kubectl get pvc -n django-app
      - name: restart 
        run: |
          echo "=== RESTART"
          kubectl delete pods -n kube-system -l app=ebs-csi-controller

          echo "=== CSI status ==="
          kubectl get pods -n kube-system | grep ebs

      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/postgres -n django-app --timeout=300s
          kubectl rollout status deployment/django -n django-app --timeout=300s
      - name: Debug postgres
        if: always()
        run: |
          echo "=== PODS ==="
          kubectl get pods -n django-app

          echo "=== DESCRIBE ==="
          kubectl describe pods -n django-app

          echo "=== LOGS ==="
          kubectl logs -n django-app --all-containers --tail=100 || true